966 - Friend disappears after adding 9+ friend
Pre: user should have 8 friends

Steps: add one more friend

ER:

friend 1 moves to the bench
friend 9 appears on the grid
AR:

friend 1 disappears. it is neither on bench nor on grid
friend 9 appears on the bench

ERROR: entity->model filling method was returning model even if nil value passed

SOLITION: added check for nil